### ISSUE TITLE
Add more examples for secret templating

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/docs#150]
The docs currently have example StorageClasses for using only fixed secret references, or only templated secret references.

It might be useful to also add an example StorageClass that combines both fixed and templated references.  

And also describe some more sample user stories that this can support.

/help

**Comment by ggriffiths** [comment]
It also seems that the docs are using the deprecated parameter keys:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast-storage
provisioner: csi-driver.team.example.com
parameters:
  type: pd-ssd
  csiNodePublishSecretName: ${pvc.annotations['team.example.com/key']}
  csiNodePublishSecretNamespace: ${pvc.namespace}
```

I'll submit a PR updating these.
